name: Telegram Media Uploader

on:
  workflow_dispatch:
    inputs:
      start_from_id:
        description: 'Start uploading from this ID'
        required: false
        default: '0'
        type: string
      google_drive_url:
        description: 'Google Drive JSON file URL (optional - uses repo secret if empty)'
        required: false
        default: ''
        type: string
  # schedule:
    # Run daily at 12:00 UTC (optional)
    # - cron: '0  * * *'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run media uploader
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
        START_FROM_ID: ${{ github.event.inputs.start_from_id || '0' }}
        GOOGLE_DRIVE_JSON_URL: ${{ github.event.inputs.google_drive_url || secrets.GOOGLE_DRIVE_JSON_URL }}
      run: |
        python telegram_uploader.py

    - name: Upload downloaded JSON (for debugging)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: media-data-json
        path: media_data.json
        retention-days: 3

    - name: Upload logs (if failed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: upload-logs
        path: |
          *.log
          error_*.txt
        retention-days: 7
